### ISSUE TITLE
[web-scripts] break up integration tests into individual task tests

### ISSUE THREAD

**Issue by fastfrwrd** [spotify/web-scripts#104]
The bloated integration test is pretty tricky to keep working at this point. In addition, some task tests would benefit a lot from being dockerized (namely the ones that make filesystem changes or depend on git). Let's split it up into individual task tests.

**Comment by josephmcasey** [comment]
Apologies if this is a little long-winded, I partly doing this for myself, so I can better understand how to best solve this.

I'm currently working on this; and, with your insight, I think I have both an understanding of the problem and a strategy. I'll explain what I have discovered with what I believe can help solve multiple obstacles to build a more complete testing strategy for this CLI. I hope you'll guide me on where I have missed the point in my diagnosis.

In my **discovery** steps, I have identified that this library lacks an E2E framework. Therefore, I believe that this has inevitably mixed the project's unit and e2e tests together under a single framework (jest).  _It is pretty understandable that a CLI library might do this because I honestly haven't seen a really javascript testing framework for CLI libraries_. However, this can pose a bit of a scaling problem because unit tests usually run use a piece of logic that shouldn't require complex utilization your local system (keeping an API port open, running an SQL DB, installing files, etc) because it shouldn't reflect the behavior of your full system, only an identifiable logical piece.

So, I believe the **solution** for this would be targeting tests that utilize the local system's OS extensively for migration to a proper E2E test suite. My current steps for how this could be done are as follows:

1) Migrate the five tests that use a `__fixtures__` directory to a root directory named `e2e`
2) Create a single Docker image which has the prerequisites file structure necessary for these tests
3) Create a step inside `.github/workflows/test.yml` that references a `.github/workflows/e2e.yml` which uses this newly created `Dockerfile` 
4) Under the root `package.json`, create a separate run-script for running the docker image locally.

-------

Any thoughts you have on this would definitely be appreciated. I'm certain I did not paint a full picture, or even a correct one; but I think the general concept of segregating unit and e2e tests is what needs to be done here... somehow, with or without docker.

**Comment by fastfrwrd** [comment]
Thanks for the thorough write up!

That all makes sense. In the past I have focused efforts on testing CLIs around integration tests (as you say e2e), because mocking filesystems et al is not an appealing approach. However, I think that in the case of web-scripts, a divided approach would make more sense, so that we could write unit tests for a lot of the edge cases while still keeping a small suite that does it all.

I hope that we can limit what goes into the e2e tests to adhere to a [testing pyramid](https://martinfowler.com/articles/practical-test-pyramid.html). From there, tests such as the ones you wrote for postinstall would be much better as unit tests; maybe even with more isolation, particularly network mocking (I hate that many of the current tests have a dependency on npm registry).

I'm not actively working on web-scripts stuff for a bit, but reworking the tests is something would be hugely beneficial. If you run forward on this, you definitely have my support!
