### ISSUE TITLE
[create-web-scripts-library] avoid the submodule

### ISSUE THREAD

**Issue by fastfrwrd** [spotify/web-scripts#124]
It's a bit fussy and manual to keep bumping the commit that is used in the `template` submodule for create-web-scripts-library.

**Comment by josephmcasey** [comment]
What would you consider to be the solution here? It feels like there are a couple of approaches that could be taken. Do you feel like the ideal approach to solve this problem is:

A) Recursively copy the contents of the submodule into the template directory
B) Write a script that automates the process of bumping the commity that is used in the template
C) Move the template into a registry and pull the template using a semver value
D) Something else

**Comment by fastfrwrd** [comment]
I feel like it's probably A), but I want to do research as to how other project scaffolds like create-next-app and create-react-app do it these days, and also see if their history has any hints as to which is best.

**Comment by fastfrwrd** [comment]
The big thing here is that they probably nest their scaffolds into the project, but we're attempting to use the relatively new Template Repo feature of GitHub to power it

**Comment by fastfrwrd** [comment]
This is less pressing with the [version replacement logic](https://github.com/spotify/web-scripts/blob/master/packages/create-web-scripts-library/src/index.ts#L37-L39) I added.
