### ISSUE TITLE
Should we format more file formats with `web-scripts format`?

### ISSUE THREAD

**Issue by mtlewis** [spotify/web-scripts#584]
Right now, the `web-scripts format` task only formats files with the extensions `js`, `jsx`, `ts`, and `tsx`. The format checking done as part of `web-scripts lint` has a similar restriction. Prettier supports passing unfiltered lists of files, and ignoring any that it doesn't know how to format via the [`--ignore-unknown`](https://prettier.io/docs/en/cli.html#--ignore-unknown) flag. This would mean that we can format files that are susceptible to spurious whitespace changes like yaml and markdown files, as well as other commonly used file types like JSON. It seems to me that Prettier is no less valuable in this file types, and in fact by extension no less valuable in files outside the `src` directory. As such:

1. Should we relax the pattern used to match files in `web-scripts format` and the format checking part of `web-scripts lint`, removing the entire extension pattern and adding `--ignore-unknown` so that Prettier silently skips files it can't format?
2. Should we also adjust the pattern so that files outside of the `src` directory are included?

I'm totally happy to open a PR for this! Just wanted to gauge interest first.

**Comment by javoire** [comment]
I think this sounds reasonable!

**Comment by charud** [comment]
I think that this sounds like a good idea in general, with two caveats:

1. When people bump to this it will pretty disruptive, since every affected file has a chance to get a major overhaul by prettier, making the diffs look pretty bad for a while. So people need to be aware that they're supposed to do a "prettier commit" once over their entire codebase after bumping.

2. I've personally had a pretty bad experience with the combination of Prettier and some non-code files, like Yaml and Markdown. Prettier is not a friend with certain Techdocs-related syntaxes for embedding code for example. So we need to make sure that this can be easily disabled for people who want to.

**Comment by mtlewis** [comment]
> 1. When people bump to this it will pretty disruptive, since every affected file has a chance to get a major overhaul by prettier, making the diffs look pretty bad for a while. So people need to be aware that they're supposed to do a "prettier commit" once over their entire codebase after bumping.

For sure, this seems like a major release only kinda thing :) 

> I've personally had a pretty bad experience with the combination of Prettier and some non-code files, like Yaml and Markdown. Prettier is not a friend with certain Techdocs-related syntaxes for embedding code for example. So we need to make sure that this can be easily disabled for people who want to.

Yep, I feel your pain on that one! Have you tried using `<!-- prettier-ignore -->` to wrap parts of the markdown file you don't want to format? Once we started doing this, managing mkdocs files became a lot less painful.
